"""Initial schema with recipes and user_recipes

Revision ID: ede6c69f37ad
Revises: 
Create Date: 2026-01-20 09:27:09.936593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede6c69f37ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_domain', sa.Text(), nullable=False),
    sa.Column('parsing_method', sa.Text(), nullable=False),
    sa.Column('recipe_data', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('parsing_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('idx_recipes_parsing_method', 'recipes', ['parsing_method'], unique=False)
    op.create_index('idx_recipes_source_domain', 'recipes', ['source_domain'], unique=False)
    op.create_index('idx_recipes_source_url', 'recipes', ['source_url'], unique=False)
    op.create_table('user_recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_data', sa.Text(), nullable=False),
    sa.Column('is_modified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_recipes_deleted', 'user_recipes', ['deleted_at'], unique=False)
    op.create_index('idx_user_recipes_recipe_id', 'user_recipes', ['recipe_id'], unique=False)
    op.create_index('idx_user_recipes_user_created', 'user_recipes', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_recipes_user_id', 'user_recipes', ['user_id'], unique=False)
    op.create_index('uq_user_recipe', 'user_recipes', ['user_id', 'recipe_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_recipe', table_name='user_recipes')
    op.drop_index('idx_user_recipes_user_id', table_name='user_recipes')
    op.drop_index('idx_user_recipes_user_created', table_name='user_recipes')
    op.drop_index('idx_user_recipes_recipe_id', table_name='user_recipes')
    op.drop_index('idx_user_recipes_deleted', table_name='user_recipes')
    op.drop_table('user_recipes')
    op.drop_index('idx_recipes_source_url', table_name='recipes')
    op.drop_index('idx_recipes_source_domain', table_name='recipes')
    op.drop_index('idx_recipes_parsing_method', table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
